name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches:
      - 'ci/**'
      - 'chore/**'
      - 'fix/**'
      - 'feat/**'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NEXT_TELEMETRY_DISABLED: 1
      # Stubbed public envs so Next.js builds deterministically in CI
      NEXT_PUBLIC_FIREBASE_API_KEY: test
      NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: test
      NEXT_PUBLIC_FIREBASE_PROJECT_ID: test
      NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: test
      NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: test
      NEXT_PUBLIC_FIREBASE_APP_ID: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node (from .nvmrc) with pnpm cache
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: pnpm

      - name: Install deps
        run: pnpm i --prefer-frozen-lockfile

      - name: Typecheck
        run: pnpm typecheck

      - name: Lint
        run: pnpm lint

      - name: Test with coverage
        run: pnpm test:ci
        env:
          # Ensure tests don't send data to external services
          NODE_ENV: test

      - name: Upload coverage reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-report
          path: coverage/
          retention-days: 30

      - name: Build (smoke)
        run: pnpm build
