name: ci
on:
  pull_request:
    branches: [ main ]
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with: { version: 9 }
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
      - name: Lint (if configured)
        if: hashFiles('.eslintrc*') != ''
        run: pnpm run lint
      - name: Typecheck (if tsconfig exists)
        if: hashFiles('**/tsconfig.json') != ''
        run: pnpm run typecheck
      - name: Build
        run: pnpm run build
