name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NEXT_TELEMETRY_DISABLED: 1
      # Stubbed public envs so Next.js builds deterministically
      NEXT_PUBLIC_FIREBASE_API_KEY: test
      NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: test
      NEXT_PUBLIC_FIREBASE_PROJECT_ID: test
      NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: test
      NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: test
      NEXT_PUBLIC_FIREBASE_APP_ID: test

    steps:
      - uses: actions/checkout@v4

      # Pin the exact Node you use locally
      - uses: actions/setup-node@v4
        with:
          node-version: '20.14.0'
          cache: 'pnpm'

      # Install pnpm explicitly so the runner can find it
      - name: Install pnpm
        run: npm i -g pnpm@9

      - name: Install deps
        run: pnpm i --prefer-frozen-lockfile

      - name: Typecheck
        run: pnpm typecheck

      - name: Lint
        run: pnpm lint

      - name: Build (smoke)
        run: pnpm build